#!/bin/sh

if [ -f /sbin/banner ]; then
/sbin/banner
else
[ -f /etc/banner ] && cat /etc/banner
fi

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

if [ -f /usr/bin/clish ]; then
CLI=`cat /proc/cmdline | grep ramfs`
if [ "x${CLI}" != "x" ]; then
/usr/bin/clish
else
CLI=`config get cli_on`
if [ "x${CLI}" = "x1" ]; then
/usr/bin/clish
fi
fi
fi

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
